sudo: true

language: ruby
rvm:
  - 2.2

addons:
  apt:
    sources:
      - chef-current-precise
    packages:
      - chefdk

install: bundler install

before_script:
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - berks install

script:
  - rubocop
  - foodcritic -f any -X spec .
  - bundle exec rspec --color --format progress
